### ISSUE TITLE
Closing a Subscription fails with a NoSuchMethodError 

### ISSUE THREAD

**Issue by mosche** [nats-io/java-nats-streaming#102]
I can consistently reproduce this issue in the test application below that only depends on `java-nats-streaming` for all the latest versions including 2.1.0.

```
[error] Exception in thread "main" java.lang.NoSuchMethodError: io.nats.client.Connection.request(Ljava/lang/String;[B)Ljava/util/concurrent/CompletableFuture;
[error] 	at io.nats.streaming.SubscriptionImpl.close(SubscriptionImpl.java:167)
[error] 	at io.nats.streaming.SubscriptionImpl.close(SubscriptionImpl.java:113)
[error] 	at test.Test.main(Test.java:35)
```
**Test code**
```java
package test;

import io.nats.streaming.*;
import java.time.Duration;

public class Test {

  public static void main(String[] args)  {
      try {
          StreamingConnectionFactory cf = new StreamingConnectionFactory("clusterId", "clientId");
          cf.setNatsUrl("nats://localhost:4222");
          StreamingConnection connection = cf.createConnection();

          SubscriptionOptions options = new SubscriptionOptions.Builder()
                  .durableName("durableName")
                  .manualAcks()
                  .ackWait(Duration.ofMinutes(1))
                  .maxInFlight(300)
                  .build();

          Subscription subscription = connection.subscribe("subject", msg -> System.out.println(msg.toString()), options);

          Thread.sleep(5000);

          subscription.close();
          connection.close();
      } catch (Exception e) {
          e.printStackTrace();
      }
  }
}
```

Besides the issue above, it isn't entirely clear to me if a durable subscription should be closed (without removing the subscription obviously) as a best practice when a client disconnects / terminates. Or if this is optional and the issue above isn't all that critical.

**Comment by sasbury** [comment]
What version of the nats library and jdk are you using?

**Comment by mosche** [comment]
I'm using `java-nats-streaming` 2.1.0, but had the same issue with 2.0.2.

Apparently there's a problem with dependencies in the pom:
https://repo1.maven.org/maven2/io/nats/java-nats-streaming/2.1.0/java-nats-streaming-2.1.0.pom

```
    <dependency>
      <groupId>io.nats</groupId>
      <artifactId>jnats</artifactId>
      <version>[2.0.0,)</version>
      <scope>runtime</scope>
    </dependency>
```

The jnats minimum requirement seems to be binary incompatible.

`Maven` resolves this alright using the latest version anyway.
However, using `sbt`, it is building against jnats 2.0.0 and fails.

So not a big deal, I can just provide the matching jnats version rather than relying on the transitive one.

**Comment by sasbury** [comment]
I will update the pom when i get a chance. Thanks for figure that out.

**Comment by mosche** [comment]
Thanks for the quick fix :)
