### ISSUE TITLE
Client can't reconnect with continuous TimeoutException

### ISSUE THREAD

**Issue by seregaSLM** [nats-io/java-nats-streaming#107]
Two instances of application work on the one server and connected to the same queue group. CPU is loaded on 90-95%. After some reconnects to the server after some slow consumer detected events one of the instance can't reconnect with infinite error:
```
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at io.nats.client.impl.NatsConnection.tryToConnect(NatsConnection.java:319)
	at io.nats.client.impl.NatsConnection.reconnect(NatsConnection.java:225)
	at io.nats.client.impl.NatsConnection.closeSocket(NatsConnection.java:471)
	at io.nats.client.impl.NatsConnection.lambda$handleCommunicationIssue$2(NatsConnection.java:428)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
I think that client can't receive pong response but why?

After restart instance can connect to the server successfully.

**Comment by sasbury** [comment]
From the stack trace it looks like something is happening in the underlying client. Let me link this over there.

https://github.com/nats-io/java-nats/issues/186

**Comment by sasbury** [comment]
which version of the libraries are you using, btw, i did do a fix for ping/pong recently.

**Comment by seregaSLM** [comment]
Using the latest docker version of nats-streaming-server and client java-nats-streaming version 2.1.1. Using OS Debian 9.6. I saw in nats console, that the client connect and after some seconds connection closed and so infinite.
Thanks.

**Comment by sasbury** [comment]
Which version of java-nats do you have, that is where i did a ping/pong fix (or maybe i broke it).

**Comment by sasbury** [comment]
can you send me the gnatsd console with -DV? Nothing is jumping out at me in the code.

Also, are you using any special connect settings or is everything basically the default?

**Comment by sasbury** [comment]
Don't worry about the log, i have one from another report, definitely something up with slow consumer handling.

**Comment by sasbury** [comment]
Fix is in the newest branch of the Java library, i am planning to release it next week and will fix this some issues in streaming as well and update it.
