### ISSUE TITLE
availability of SetConnectionLostHandler on Java driver

### ISSUE THREAD

**Issue by protheusfr** [nats-io/java-nats-streaming#113]
Hello all,

Is the `SetConnectionLostHandler` option available on Java client like in Go one ?

**Comment by sasbury** [comment]
The underlying nats connection has a ConnectionListener, you can set it on the Options for the streaming connection as well.

**Comment by protheusfr** [comment]
Thank you @sasbury but I don't find any way to use it.
I've set the connection timeout :  
```scala
    val cf = new StreamingConnectionFactory(clusterName, clientName)
    cf.setNatsUrl(url)
    cf.setConnectTimeout(10,TimeUnit.SECONDS)
    for {
      sc <- Try(cf.createConnection()).toEither.left.map(_.getMessage)
    } yield sc
```
But I don't understand how to specify the connection lost handler.

**Comment by sasbury** [comment]
Ah, you have to use the connect method that takes options:

public static StreamingConnection connect(String clusterId, String clientId, Options opts)

Keep this open and i can add that to the connection factory as well, or if you want to do a PR that is cool too.

**Comment by protheusfr** [comment]
Hmmm I'm sorry but `StreamingConnection` interface hasn't `connect` method (in my version 2.1.2).
The `StreamingConnectionImpl` has one and `StreamingConnectionImpl` can be instantiated with `options` and `options` can contain a `ConnectionListener`.
But it's not clear how to use it.

I guess I must check the connection status before each operation ?
like : 
```scala
  def Publish(sc: StreamingConnection, subject: String, content: Array[Byte]): Either[String, Unit] = {
    if (sc.getNatsConnection.getStatus != Connection.Status.CONNECTED) {
      return Left("connection lost")
    } else {
      Try(sc.publish(subject, content)).toEither.left.map(_.getMessage)
    }
  }
```

Is there no way to define at connection time a function that can be automatically called in case of connection loss ?
