### ISSUE TITLE
Java NATS Streaming client is publishing messages when two of three nodes in NATS Streaming Server cluster are down

### ISSUE THREAD

**Issue by willowish** [nats-io/java-nats-streaming#116]
Hi!
I'm facing  and issue with java-nats-streaming. I have created cluster of NATS Streaming, which contains 3 nodes. I have created 2 clients, one for publishing messages and another for reading them.
Scenario:
1) all 3 nodes are up
2) publisher starts to publish messages 
3) subscriber is receiving messages
4) 2 of 3 nodes are going down
5) publisher is still sending messages (lets call them Down Messages)
6) subscriber does not received messages
7) all 3 nodes are up
8) publisher is still sending messages 
9) subscriber is receiving messages, but Down Messages are missing

Scenario when all nodes are down is identical. 

# Expected Behavior

Java NATS Streaming client should stop publishing messages when two of three nodes in NATS Streaming Server cluster are down or at least resend them.
Java NATS Streaming client should stop publishing messages when ALL nodes in NATS Streaming Server cluster are down or at least resend them.

# Current Behavior

Java NATS Streaming client is publishing messages when two of three nodes in NATS Streaming Server cluster are down.

Java NATS Streaming client is publishing messages when ALL nodes in NATS Streaming Server cluster are down. 

It doesn't resend them when nodes are restored, or rather streaming client doesn't know that it should wait for more than half of nodes to start publishing again (I guess).

## Context

My setup: 
	- 3 NATS Streaming nodes (in docker) in latest version. With conf:
```	
streaming: {
	  cluster_id: nats-sk
	  cluster {
	    node_id: "nats-0"
	    peers: ["nats-1", "nats-2"]
	  }
	}

	authorization {
	  ADMIN = {
	    publish = ">"
	    subscribe = ">"
	  }
	  REQUESTOR = 
	 {   publish = ["incoming", "_STAN.>", "_INBOX.>"]
	    subscribe = ["OUT_.>", "_INBOX.>", "_STAN.>"]
	  }

	  users = [
	    {user: admin, password: admin, permissions: $ADMIN}
	    {user: regular, password: regular, permissions: $REQUESTOR}
	  ]
	}

	tls {
	  cert_file: "/nats-sk-test/nats-0/cert.pem"
	  key_file: "/nats-sk-test/nats-0/key.pem"
	  timeout: 1
	  verify: false
	}

	port: 4222
	cluster {
	  listen: 0.0.0.0:6222
	  routes: ["nats://172.17.0.5:6223", "nats://172.17.0.6:6224"]
	}
```	

	second node (I skipped auth and tls section):

```	
	streaming: {
	  cluster_id: nats-sk
	  cluster {
	    node_id: "nats-1"
	    peers: ["nats-0", "nats-2"]
	  }
	}
	port: 4222
	cluster {
	  listen: 0.0.0.0:6223
	  routes: ["nats://172.17.0.4:6222", "nats://172.17.0.6:6224"]
	}
```	

	third one:

```	
	streaming: {
	  cluster_id: nats-sk
	  cluster {
	    node_id: "nats-2"
	    peers: ["nats-0", "nats-1"]
	  }
	}
	port: 4222
	cluster {
	  listen: 0.0.0.0:6224
	  routes: ["nats://172.17.0.4:6222", "nats://172.17.0.5:6223"]
	}
```	

Client:
	-java-nats-streaming: 2.1.3
	-jnats: 2.4.1 I also tried 2.1.X

Connection creation:

```
StreamingConnection createNatsConnection() {
	try {
		Connection connection = getConnection(urls, username, password);
		StreamingConnectionFactory cf = new StreamingConnectionFactory(clusterId, clientId);
		cf.setNatsConnection(connection);
		cf.setAckTimeout(Duration.ofMillis(300));
		return cf.createConnection();
	} catch (Exception e) {
		log.error(e.getMessage());
		return null;
	}
}
```

```
private Connection getConnection(List<String> urls, String username, String password) throws IOException, InterruptedException, NoSuchAlgorithmException {
		Options o = new Options.Builder()
				.servers(urls.toArray(new String[0]))
				.userInfo(username, password)
				.sslContext(SSLContext.getDefault())
				.connectionTimeout(Duration.ofMillis(400))
				.maxReconnects(-1).build();
		return Nats.connect(o);
}

```

```
// `connection` is an instance of StreamingConnection
connection.publish(subject, objectMapper.writeValueAsBytes(event));

```

I have found similliar problem on stackoverflow: https://stackoverflow.com/questions/53190596/java-nats-streaming-publishing-messages-after-server-reconnects

Could you address this issue?

**Comment by kozlovic** [comment]
Your assumption is incorrect. If two out of the three nodes are down, there is a loss of leader in the cluster. Messages will not be handled and client library will receive either an explicit error (for instance server was trying to store but lost leadership) or simply timeout. It is responsibility for the user to decide what to do with error'ed published messages.

In cluster mode, since we use RAFT, the tolerance of failure is (N-1)/2, so if N is 3, it can tolerate a failure of 1 node, after that, there is no progress since there is no leader.
