### ISSUE TITLE
Get underlying nats connection from stan connection

### ISSUE THREAD

**Issue by bkim54** [nats-io/java-nats-streaming#29]
The method `getNatsConnection()` on io.nats.stan.ConnectionFactory only returns a user set nats connection. 

Other clients (.net and node) support returning the actual nats connection stan uses.

**Comment by mcqueary** [comment]
Thanks for pointing this out, Bill. We’ll fix that and roll a new release.

-- 
Larry McQueary | Director, Messaging Technology
larry@apcera.com <mailto:larry@apcera.com> | @mcqueary | github.com/mcqueary <http://github.com/mcqueary>
