### ISSUE TITLE
Timer already cancelled error

### ISSUE THREAD

**Issue by zshamrock** [nats-io/java-nats-streaming#41]
Occasionally I get the following error in the log:

![nats streaming timer issue](https://cloud.githubusercontent.com/assets/1122268/21303427/a32e9108-c5be-11e6-8107-4d703433f573.png)

Is it known issue in the NATS streaming client, or what could be cause of this issue, and is it possible to recover from this? Re-create the connection? 

#40 might be related

**Comment by zshamrock** [comment]
Using NATS streaming `0.3.0` version, and NATS streaming client `0.4.1` version

**Comment by zshamrock** [comment]
Is the development of the client still in progress? @mcqueary @kozlovic ? Any ideas on the error above?

**Comment by ColinSullivan1** [comment]
@zshamrock , development is still in progress, and one of us will look into this - apologies for the delay.  Can you describe what is going on in your environment when you encounter this?

**Comment by ColinSullivan1** [comment]
@zshamrock ,  I'll be curious to see if upgrading solves your problem.  This could very well be a race condition of sorts.  @mcqueary, any thoughts on this issue?

**Comment by zshamrock** [comment]
This was starting to happen more often. Any ideas on possible cause?

**Comment by kozlovic** [comment]
@zshamrock @mcqueary My guess is that an uncaught exception happens in the `java.util.Timer` main loop that causes it to stop and prevent any new timer scheduling. Since `processAckTimeout()` is the only function that seems to be invoked from `ackTimer`, I would ensure that this function has a `try{} catch(Throwable){}` (and log the exception caught) but never let an exception go through otherwise it will kill the shared timer thread. Notice that it is especially important because `processAckTimeout()` ends up invoking a user provided callback...

**Comment by zshamrock** [comment]
Also I see a lot of the following in the NATS streaming itself:

```
... (a lot of similar before)
[TRC] STAN: [Client:1f43ae79-c4ba-407e-95e8-8ee349842e09] Acking Publisher subj=session.f1bebd85-d420-11e6-8128-f6fc4aae4f88 guid=wrK99Ig3ktpbGFywbtPzn0
... (a lot of similar after)
```

Not sure if it is normal/expected, or whether it is due to misbehaving Java client.

**Comment by zshamrock** [comment]
Also @kozlovic I have not looked yet into the internals of the implementation of the Java client, but should we use `Executor` instead of `java.util.Timer` for the scheduling? Again, don't know the exact use case, but it sounds like `Executor` suits better for this kind of things.

**Comment by kozlovic** [comment]
@zshamrock That's a trace that says that the server is ack'ing back a published message (with given guid) on the give subject. So as long as you are publishing messages, this is normal ;-)

**Comment by zshamrock** [comment]
@kozlovic do you know what could be cause of 

> My guess is that an uncaught exception happens in the java.util.Timer main loop that causes it to stop and prevent any new timer scheduling. 

Is it an issue in the `java.util.Timer` itself, or the way it was used, or something else?

**Comment by zshamrock** [comment]
Ok, so indeed looks like some exception is happening in `processAckTimeout` which makes timer to be canceled. Then the question what kind of the exception, why, and is it safe to ignore it, i.e. will it affect the communication with the server?

**Comment by kozlovic** [comment]
> Is it an issue in the java.util.Timer itself, or the way it was used, or something else?

This is a pitfall of `java.util.Timer`. If the task invoked throws an exception, it will kill the timer's thread, so no more timer tasks can be executed nor scheduled. For instance, in the AckHandler callback that you provide to the publish call, if your code throws a `RuntimeException` for instance, then you should see this exception pop-up at the next publish.

**Comment by zshamrock** [comment]
@kozlovic @mcqueary are you planning to some work in this direction today or tomorrow? If no, then I will try to comment the PR, to wrap `processAckTimeout` into `try/catch`, not ideal, but probably better than nothing for now. If this is considered as an appropriate short term fix?
