### ISSUE TITLE
Durable sub queue group may miss a message if a group member crashes

### ISSUE THREAD

**Issue by mcqueary** [nats-io/java-nats-streaming#42]
This is explained further in the related Slack conversation but here's the synopsis: start 3 subscribers using the below app. Kill one with `CTRL-C`. There is a seqno gap (1 message).

[pom.txt](https://github.com/nats-io/java-nats-streaming/files/671557/pom.txt)
[App.java.txt](https://github.com/nats-io/java-nats-streaming/files/671559/App.java.txt)
![missingmsg](https://cloud.githubusercontent.com/assets/6993964/21464130/e1176a8c-c931-11e6-9b51-ce47f9e6b41e.png)

**Comment by ae6rt** [comment]
Here is how I was sending messages, fwiw:

```
while : ; do ./stan-pub -c test-cluster -id goclient foo "$(date)" && sleep 5; done
```

**Comment by ae6rt** [comment]
The full Java app:

```
package com.xoom.inf.nats;

import io.nats.stan.Connection;
import io.nats.stan.ConnectionFactory;
import io.nats.stan.Message;
import io.nats.stan.MessageHandler;
import io.nats.stan.Subscription;
import io.nats.stan.SubscriptionOptions;

import java.util.concurrent.CountDownLatch;

final public class App {
    public static void main(final String[] args) throws Exception {
        final String clientId = args[0];
        final boolean unsub = Boolean.parseBoolean(args[1]);

        final ConnectionFactory cf = new ConnectionFactory();
        cf.setNatsUrl("nats://localhost:4222");
        cf.setClusterId("test-cluster");
        cf.setClientId(clientId);

        final Connection sc = cf.createConnection();

        final Subscription sub = sc.subscribe("foo", "thequeue", new MessageHandler() {
            public void onMessage(Message m) {
                try {
                    m.ack();
                    System.out.printf("Received a message (seq=%d): %s\n", m.getSequence(), new String(m.getData()));
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }, new SubscriptionOptions.Builder().setDurableName("durableQ")
                                            .startWithLastReceived()
                                            .setManualAcks(true)
                                            .build());

        final CountDownLatch latch = new CountDownLatch(1);
        Runtime.getRuntime().addShutdownHook(
                new Thread() {
                    public void run() {
                        try {
                            if (unsub) {
                                sub.unsubscribe();
                                sc.close();
                            } else {
                                System.out.println("Skipping unsubscribe and close");
                            }
                        } catch (final Exception e) {
                            throw new RuntimeException(e);
                        } finally {
                            latch.countDown();
                        }
                    }
                }
        );

        latch.await();
    }
}
```

**Comment by ae6rt** [comment]
Finally, how I started the server

```
docker run -it -p 4222:4222 -p 8222:8222 nats-streaming:0.3.6 -DV
```

**Comment by ae6rt** [comment]
I performed a similar set of operations using the same server, but this time with the stock stan-sub.go Go client to play the subscriber role.  I believe the missing message effect obtains in this case, too.  

Run three subscribers, and kill one with prejudice with 'kill -9', such that its signal handler does not run.  afaict, message seq==25 is missing.

![image](https://cloud.githubusercontent.com/assets/392176/21467764/1597e5ae-c9ad-11e6-870f-e54df9998c6a.png)

**Comment by kozlovic** [comment]
@ae6rt As explained in the Slack channel, the server assigns the messages to the member that has crashed since it does not know that it has crashed (there is no direct TCP connection between clients and server). So only after the server-to-client heartbeat mechanism tells the server that the client is gone that those messages get redelivered to the remaining members. The server version `0.3.6` allows you to easily tune the heartbeat values to lower the time it takes to discover that the client is gone. 
I have created issue https://github.com/nats-io/nats-streaming-server/issues/220 in the server to track this. I am closing this issue for now. Thanks!
