### ISSUE TITLE
Should travis build run integration tests as well

### ISSUE THREAD

**Issue by zshamrock** [nats-io/java-nats-streaming#46]
Currently it looks like, Travis build runs only unit tests, which is good, but probably not good enough. 

Should Travis also run by default and integration tests as well?

**Comment by mcqueary** [comment]
Yes, that's always been the intent. Look for this change in the near future.

**Comment by sasbury** [comment]
Current builder runs tests against streaming server, not sure if that is what was requested, but closing. Reopen if i missed something.
