### ISSUE TITLE
SubscriptionOptions$Builder should be Serializable

### ISSUE THREAD

**Issue by laugimethods** [nats-io/java-nats-streaming#51]
To avoid `Exception during serialization: java.io.NotSerializableException: io.nats.stan.SubscriptionOptions$Builder`, `io.nats.stan.SubscriptionOptions$Builder` should be serializable (as well as `io.nats.stan.SubscriptionOptions`, which might impact other projects).

See https://github.com/Logimethods/nats-connector-spark/pull/3 .

**Comment by mcqueary** [comment]
Laurent, thanks for raising this issue. Definitely an oversight on my part. I'll fix.

**Comment by ColinSullivan1** [comment]
@laugimethods , Apologies for delay.  

First, it's great to see NATS streaming being added to the spark connector!

I'd like to step back and ask - why do you need SubscriptionOptions and/or its builder to be serializable?  While java serialization is robust, it can affect other projects as you mentioned, can introduce compatibility issues, and we strongly prefer to keep the NATS streaming API as simple as possible moving forward.

Would encapsulating or subclassing to a serializable class of yours meet your needs?  Long term, you'd have more flexibility and control in your project.

That being said, I'm certainly happy to discuss if there is a compelling reason to introduce this change...

Thanks,
Colin

**Comment by laugimethods** [comment]
@ColinSullivan1, the Spark "code" (could be Java or Scala) - including the configuration of the subscription to NATS - is not run locally, but sent to the Spark Workers to be executed remotely (and therefore needs to be serializable).

We would like to be able to use the Spark to NATS connector that way:
```
SubscriptionOptions.Builder optsBuilder = new SubscriptionOptions.Builder().setDurableName(DURABLE_NAME);
NatsStreamingToKeyValueSparkConnectorImpl connector = 
		NatsToSparkConnector
			.receiveFromNatsStreaming(String.class, StorageLevel.MEMORY_ONLY(), CLUSTER_ID)
			.withNatsURL(STAN_URL)
			.withSubscriptionOptionsBuilder(optsBuilder)
			.withSubjects("SUBJECT")
			.storedAsKeyValue();
```
We might implement the `.withSubscriptionOptionsBuilder(optsBuilder)` so that this configuration is automatically transformed into some serializable code, but writing an _ad hoc_ serialization/deserialization is painful to write in the first place, and even more to maintain... Especially since we are not talking about a simple Java Bean, but an inner class.

Also, having a subclass that is serializable could be helpful, but the `SerializableSubscriptionOptions.Builder optsBuilder = new SubscriptionOptions.SerializableBuilder().setDurableName(DURABLE_NAME);` would then diverge from the conventional way of creating Nats subscription options, which I prefer to avoid.

**Comment by ColinSullivan1** [comment]
@laugimethods , I can see how you could use this.  However, at this time I feel its best to stick with the NATS tenet of simplicity and leave it up to the application/user to serialize and pass configuration around.  It looks like you have a way to do this in the PR you mentioned above.  

I realize this isn't ideal for you, but on our side I'm concerned this could create issues for us in the future should we need to change internals of the SubscriptionOptions class.  As the NATS streaming client continues to mature, I'd be happy to revisit this.

Regards,
Colin

**Comment by laugimethods** [comment]
@ColinSullivan1, I take note of your answer as I understand that you don't want to take any compatibility risk. 

However, you should make sure in the next main version that all the classes that can be considered as configuration are serializable since it is potentially a requirement in any distributed environment (like Hadoop, Akka actors, etc.).

In the meantime, could you move to `protected` the `private SubscriptionOptions(Builder builder)` constructor of `SubscriptionOptions` so that I can extend that class?

Best regards,
Laurent

**Comment by ColinSullivan1** [comment]
@laugimethods ,  I'd rather make the options serializable than expose that constructor right now.  ;)  I'll take this up with the team, and get back to you.  We are anticipating some internal changes to the client, and will see if serialization fits moving forward.  I'll get back to you.

Thanks,
Colin

**Comment by laugimethods** [comment]
Had been solved by https://github.com/nats-io/java-nats-streaming/pull/56
