### ISSUE TITLE
Any plans for the new release?

### ISSUE THREAD

**Issue by zshamrock** [nats-io/java-nats-streaming#54]
Hi, guys, the last 0.4.1 version was released on November 2016, so almost 8 months ago. Any plans for the new release in near future?

**Comment by jhernandezme** [comment]
Wondering the same thing.

**Comment by ColinSullivan1** [comment]
@zshamrock , @jhernandezme , Thank you for asking - it has been awhile.  We're currently evaluating what should go into a new release now, and will let you know soon.

**Comment by zshamrock** [comment]
Maybe when it is released also to mention with with NATS streaming server it is compatible, as it looks like the client and the server are developing at the different speed, and it is not clear whether the latest client works with the latest server release.

Probably the same applies for the NATS (not streaming) too.

**Comment by ColinSullivan1** [comment]
@zshamrock , Absolutely.  At this point clients should work with any version of the NATS streaming server (and NATS server), although some older clients may not be able to take advantage of newer features in the server.  If there is breaking change, it will be considered a bug unless otherwise noted.

**Comment by zshamrock** [comment]
Great! Good to know.

**Comment by sasbury** [comment]
Released 2.0.1 today - the major version change is to account for the dependency on 2.0 of the client library which had breaking changes, and may effect some exception types in the streaming library.
