### ISSUE TITLE
DEFAULT_MAX_PUB_ACKS_IN_FLIGHT has wrong value

### ISSUE THREAD

**Issue by zshamrock** [nats-io/java-nats-streaming#58]
In the `NatsStreaming` class `DEFAULT_MAX_PUB_ACKS_IN_FLIGHT` is defined as the following:

```
static final int DEFAULT_MAX_PUB_ACKS_IN_FLIGHT = 2 ^ 14; // 16384
```

where `^` is the XOR (not power function), and so results in value `12` and not the expected `16384`.

Instead `1 << 14` could be used instead or just simply the value itself.

**Comment by ColinSullivan1** [comment]
Resolved by #59.
