### ISSUE TITLE
Java 7 support

### ISSUE THREAD

**Issue by schicks** [nats-io/java-nats-streaming#61]
I'm trying to use this to build a connector between a Java 7 application and the rest of my tools communicating using nats. However, building my code on java 7 throws `unsupported major/minor version 52`. How difficult would it be to support use in Java 7?

**Comment by ColinSullivan1** [comment]
@schicks , thank you for raising this issue.  We'll look into it.

**Comment by sasbury** [comment]
Our plan is to stay on 8+, hopefully that is ok (since this bug got left behind).
