### ISSUE TITLE
[Documentation] Add more detailed explanations and examples of the driver features

### ISSUE THREAD

**Issue by jebbench** [nats-io/java-nats-streaming#62]
I have found the following to be missing from the documentation:

- How to create a connection, the existing documentation simply states:
  ```
   ConnectionFactory cf = new ConnectionFactory(clusterID, clientID);
   Connection sc = cf.createConnection();
   ```
   but doesn't mention how to set the host, port, username or password.

**Comment by ColinSullivan1** [comment]
@jebbench , thanks for raising this!  We do need to clear up the documentation.

**Comment by ColinSullivan1** [comment]
Noting another user has requested this.

**Comment by sasbury** [comment]
Closing this in favor of the larger issue. I did add a few docs.
