### ISSUE TITLE
The latest SNAPSHOT.jar is from May, and doesn't include the most recent MR from Sept. 7.

### ISSUE THREAD

**Issue by eigood** [nats-io/java-nats-streaming#64]

**Comment by sachinwalia2k8** [comment]
I saw that too and unfortunately had to resort to create my own local build.
To the authors if you could please update the release version as well as the documentation then it'd be awesome. Also please publish a link to javadoc as well.

**Comment by ColinSullivan1** [comment]
@sachinwalia2k8 , @eigood , thank you for raising this issue.  We are overdue for a snapshot and a release, and will work on this.  Stay tuned.

**Comment by ColinSullivan1** [comment]
I've updated the most recent snapshot.
