### ISSUE TITLE
Slowness when publishing to multiple subjects

### ISSUE THREAD

**Issue by ajglenn** [nats-io/java-nats-streaming#65]
I have been testing with nats streaming v0.4.0 with java client v0.4.1 and found some odd behavior when publishing data to multiple subjects.  Our application works a stream of data that is published to nats streaming being backed by file(s).  We have implement the slice file script so to gain control of those files and perform additional processing.

The odd behavior happens when we are sending a number of events to multiple subjects on this single thread.  At a point when we reach 2000 messages a second that are then split and sent to different subjects the response time of the publish method increases.  The publish method is called with an AckHandler so should be async.  This increase it still within the milliseconds range but is noticeable when pushing the message rate much higher.  To contrast this, if we publish all of the messages to a single subject we do not experience an increase in response time on the publish method.

Should we expect that when calling multiple subjects there would/could be an increase in response time from publish?  Is there a correlation between the number of subjects and the possible response time of the publish method call?

**Comment by ColinSullivan1** [comment]
@ajglenn , how many subjects are in publishing to?

**Comment by ajglenn** [comment]
In our test we were publishing to about 12 subjects.

**Comment by ColinSullivan1** [comment]
@ajglenn , thank you.  This is could be behavior on the server side, but is something we'll need to check out.

**Comment by sasbury** [comment]
Closing, since we have moved many versions ahead of the report. Please reopen and let me know the latest numbers if you still see a problem.
