### ISSUE TITLE
Providing an incorrect cluster id results in a timeout exception

### ISSUE THREAD

**Issue by jebbench** [nats-io/java-nats-streaming#70]
Creating a NATs Streaming connection using an incorrect cluster id will result in a timeout exception.

```
Caused by: java.io.IOException: stan: connect request timeout
	at io.nats.streaming.StreamingConnectionImpl.connect(StreamingConnectionImpl.java:127)
	at io.nats.streaming.NatsStreaming.connect(NatsStreaming.java:83)
```

This is a little misleading - I spent a couple of hours today tying to figure out why my connect was timing out when it was just a typo in my config.

A "Incorrect cluster id." message would be very helpful.

**Comment by ColinSullivan1** [comment]
@jebbench , thank you for raising this.  I can understand how this could be confusing in the case you described.  While the error is correct, we can add troubleshooting documentation around this case.

Related to #69

**Comment by evoxmusic** [comment]
Sorry to comment this old thread, but yes the error message is not obvious.
