### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by Nargarnd** [nats-io/java-nats-streaming#75]
I'm trying to build java-nats-streaming on my Windows as it's specified on the installation section, but i'm getting an error on the build process.
There is a log attached to this message with the complete error.

[log.txt](https://github.com/nats-io/java-nats-streaming/files/1589046/log.txt)

**Comment by ColinSullivan1** [comment]
@Nargarnd , thank you for raising this.  The source looks to be building, but there are errors trying to download the NATS streaming server for testing.  We'll take a look.

**Comment by ColinSullivan1** [comment]
@Nargarnd , while we resolve this, a workaround is to install the NATS streaming server manually (or build it) and ensure it is in your `%PATH%`.  A link to download the windows binaries can be found [here](https://github.com/nats-io/nats-streaming-server/releases/download/v0.7.0/nats-streaming-server-v0.7.0-windows-amd64.zip).

**Comment by sasbury** [comment]
Can you please retry with 2.0.1, we moved from Maven to Gradle which hopefully fixed this issue. I will leave it open just in case.
