### ISSUE TITLE
StreamingConnectionFactory is not visible

### ISSUE THREAD

**Issue by Nargarnd** [nats-io/java-nats-streaming#76]
It's me again, sorry for been a pain in the ass, but after resolving my "Error on build " problem I have encounter a new obstacle in my programming duties.

I have added java-nats-streaming to my pom.xml and configure it to use Snapshots, as explained in the Installation section, here you can see the code I mentioned:

pom.xml:
...

`        <dependency>
            <groupId>io.nats</groupId>
            <artifactId>java-nats-streaming</artifactId>
            <version>0.5.0-SNAPSHOT</version>
        </dependency>`

...

        <profile>
            <id>allow-snapshots</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <repositories>
                <repository>
                    <id>snapshots-repo</id>
                    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
                    <releases><enabled>false</enabled></releases>
                    <snapshots><enabled>true</enabled></snapshots>
                </repository>
            </repositories>
        </profile>
...

Until here, everything seems ok, eclipse detects the java-nats-streaming 0.5.0 SNAPSHOT dependency so I tried to write a simple programm to check if everything is fine. 
The problem is that when I copied the "Basic Usage" code to tried it, I get an error saying "StreamingConnectionFactory is not visible", I thougth that was weird, but maybe i didn't import something so I added "import io.nats.streaming.*;" at the top of the class to import everything but the error didn't disappear.

Finally I checked where the StreamingConnectionFactory class should be, according to the javadoc it should be in io.nats.streaming.StreamingConnectionFactory but if I add "import io.nats.streaming.StreamingConnectionFactory;" I get an error like if it didn't exist.

So my questions are: 
1- Isn't this class in the java-nats-streaming 0.5.0 SNAPSHOT? 
2- Have I done something wrong?
3- Is there other way to create a StreamingConnection to try to send some messages?

**Comment by ColinSullivan1** [comment]
@Nargarnd , you aren't being a pain, not at all; and apologies for the inconvenience.  You aren't the first to run into this.  Check out https://github.com/nats-io/java-nats-streaming/pull/63 - the class should be public in master branch.

Until the next release, you can use the `NatsStreaming.connect(clusterId, clientId, options)` API to connect.  Some example usage can be found [here](https://github.com/nats-io/java-nats-streaming/blob/0.5.0/src/test/java/io/nats/streaming/examples/Publisher.java#L57), and javadoc [here](http://static.javadoc.io/io.nats/java-nats-streaming/0.5.0/io/nats/streaming/NatsStreaming.html#connect-java.lang.String-java.lang.String-).

**Comment by Nargarnd** [comment]
Thank you Colin, I've been able to create a StreamingConnection that way and now I have an small java program which creates subscribers for a specific subject that is more or less complete, but now I'm having another problem related to the StreamingConnection.

When the conection is been created with the NatsStreaming.connect(clusterId, clientId, options) method I get this log in the console:

12:29:42.035 [Thread-0] DEBUG io.nats.client.ConnectionImpl - Connecting to nats://localhost:4222
12:29:42.039 [Thread-0] DEBUG io.nats.client.ConnectionImpl - Opening nats://localhost:4222
12:29:42.050 [Thread-0] DEBUG io.nats.client.TcpConnection - socket tcp_nodelay: true
12:29:42.050 [Thread-0] DEBUG io.nats.client.TcpConnection - socket recv buf size: 2097152
12:29:42.050 [Thread-0] DEBUG io.nats.client.TcpConnection - socket send buf size: 2097152
12:29:42.052 [Thread-0] DEBUG io.nats.client.ConnectionImpl - Connected to nats://localhost:4222
12:29:42.179 [readloop] DEBUG io.nats.client.ConnectionImpl - readloop starting...
12:29:42.180 [flusher] DEBUG io.nats.client.ConnectionImpl - flusher starting...
12:29:42.324 [Thread-0] DEBUG io.nats.client.ConnectionImpl - Starting subscription for subject '_INBOX.DABDZRNtXyf4KS19Acv1Oj'
12:29:44.369 [Thread-0] DEBUG io.nats.client.ConnectionImpl - close(CLOSED, true)
12:29:44.370 [readloop] DEBUG io.nats.client.ConnectionImpl - Exception in readloop(): 'Socket closed' (state: CLOSED)
12:29:44.370 [readloop] DEBUG io.nats.client.ConnectionImpl - readloop interrupted
12:29:44.370 [flusher] DEBUG io.nats.client.ConnectionImpl - flusher interrupted
12:29:44.370 [readloop] DEBUG io.nats.client.ConnectionImpl - readloop exiting
12:29:44.370 [flusher] DEBUG io.nats.client.ConnectionImpl - flusher exiting
java.io.IOException: stan: connect request timeout
	at io.nats.streaming.StreamingConnectionImpl.connect(StreamingConnectionImpl.java:131)
	at io.nats.streaming.NatsStreaming.connect(NatsStreaming.java:86)
	at viewScada.serverCommunication.Subscriber.run(Subscriber.java:79)
	at java.lang.Thread.run(Unknown Source)
12:29:44.371 [jnats-subscriptions] DEBUG io.nats.client.ConnectionImpl - Interrupted in waitForMsgs

So there are two things that I don't understand in here
It says "Starting subscription for subject '_INBOX.DABDZRNtXyf4KS19Acv1Oj'" but thats not the subject that i'm using.

Why does the socket close? (Exception in readloop(): 'Socket closed')

I think the problem is the socket closing itself, but I don't have any idea about how to solve it.

**Comment by ColinSullivan1** [comment]
@Nargarnd , Are the cluster-ids being used for your client and server the same?

**Comment by sasbury** [comment]
Closing since this is over a year old, please reopen and let me know if you are still having an issue.
