### ISSUE TITLE
can't find sources for java-nats 1.1-SNAPSHOT

### ISSUE THREAD

**Issue by tul** [nats-io/java-nats-streaming#78]
java-nats-streaming 0.50 uses jnats 1.1-SNAPSHOT, but this appears to be a release which has no source artefacts on maven, and the java-nats repo doesn't have a corresponding git tag for this either.

Apologies if I've missed something, but it would be super handy to be able to get the exact source for released jars.

Thx

**Comment by sasbury** [comment]
2.0.1 is out, and the sources are there. I am going to close, but reopen if we need 1.1 as well for some reason.
