### ISSUE TITLE
Nats throwing a concurrent modification error

### ISSUE THREAD

**Issue by Aiqbal1234** [nats-io/java-nats-streaming#81]
im getting the following exception, I can see how this would happen unless the connect() method is being called twice? 

java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:907)
at java.util.ArrayList$Itr.next(ArrayList.java:857)
at io.nats.client.ConnectionImpl.connect(ConnectionImpl.java:407)

Possibly updating the srvpool list (setupServerPool()), while another thread is in the loop. 

ConnectionImpl class:

Connection connect() throws IOException {
        // ...
        IOException returnedErr = null;

        setupServerPool();      // can possibly update the list

        mu.lock();
        try {
            for (Srv srv : srvPool) {    // exception thrown here
            this.setUrl(srv.url);
            ....

**Comment by sasbury** [comment]
Closing as out of date, let me know if yous ee something like this in the latest release.
