### ISSUE TITLE
NATS streaming client doesn't publish the events received when the server was down

### ISSUE THREAD

**Issue by zshamrock** [nats-io/java-nats-streaming#84]
Let me explain.

For the NATS client (not the streaming one) there are options (more precisely for the connection factory, but they are later passed as the `Options` to the client instance):

```
...
# maximum number of reconnect attempts (default 60)
messaging.connection.max.reconnect=60
# pending message buffer that is used for buffering messages that are published during a disconnect/reconnect (default 8388608)
messaging.connection.reconnect.buf.size=8388608
# wait time before attempting reconnection to the same server (default 2000)
messaging.connection.reconnect.wait.ms=2000
# connection timeout (default 2000)
messaging.connection.timeout.ms=2000
...
```

The one is in interest of this discussion is `messaging.connection.reconnect.buf.size`, which allows the client to keep the messages, until the connection to the server is re-established.

I've run small demo, with the NATS server running inside the docker, stopped that instance, published couple of the messages, started the server, and was able to receive the messages sent after the server is up again (i.e. the client did burst publishing as soon as the connection is back).

When done the same for the NATS streaming server, I don't get back any of these messages, although what I see in the source code the underlying NATS connection utilized by the NATS streaming connection should respect this property. But looks like it doesn't.

So is this the feature/specifics of the NATS streaming client or actually a bug?

**Comment by sasbury** [comment]
I dont have a unit test for this, i don't think, but one issue may be the ack timeout. If the streaming library doesn't get an ack in time it will "fail" the publish. During reconnect that could result in something weird I suspect.

Can you try this on 2.0.1, and I will leave this open for comments and to remind me to build some tests around it.

**Comment by karthikraman22** [comment]
I have the same problem too. The messages don't get sent to the server after the streaming server restart. I am using java client version 2.1.1

**Comment by sasbury** [comment]
ok, i read again now I think I may no what happened. The streaming library should have sent the messages, but the streaming library doesn't autoreconnect for subscriptions, so it is possible that the messages weren't received. Can you confirm this bug with nats-sub ">" that nothing went out.

Closing for now, but ok to reopen if you can confirm.
