### ISSUE TITLE
Default ErrorListener on the NATS connection if no NATS connection is configured

### ISSUE THREAD

**Issue by reinkrul** [nats-io/java-nats-streaming#93]
By default a NatsConnection does not have an ErrorListener configured. Also, in java-nats-streaming it's also not to configure an ErrorListener apart from configuring a NatsConnection yourself. This causes a problem when following the example code: if an unhandled exception is thrown in onMessage, it gets eaten by the java-nats-streaming and jnats API. From the developer perspective, the message is never delivered, suspecting some configuration or network issue (which isn't the case).

In my opinion, application exceptions should never, by default, be eaten by a framework/library. Usability of this library would be improved would it set a default NATS ErrorListener which at least logs the exception.

For now we do a catch-log-rethrow (an anti-pattern).

For the rest, great work on the server & client library though 👍

**Comment by sasbury** [comment]
I missed this on 2.0.2, I will take a look for the next release.

**Comment by sasbury** [comment]
I am hesitant to write to logs from within the library. But I agree there is something here.

I am working on a fix where you can pass error and connection handlers to the Streaming Connection options, and those pass down to the Nats connection. This will make it easier to put your own error listener that logs. Once I get it tested and checked in, let me know what you think.

**Comment by ColinSullivan1** [comment]
For some history, we once had SLF4J log support in the NATS java clients, but in the interest of simplicity and reducing third party dependencies, we removed it.  I do agree that swallowing exceptions can be problematic for application developers, but at the same time, swallowing exceptions allows the NATS libraries to be resilient.

+1 for the option to to surface uncaught application code exceptions in an application provided error callback.
