### ISSUE TITLE
Calling Subscription#close() will unsubscribe/remove durable

### ISSUE THREAD

**Issue by fajran** [nats-io/java-nats-streaming#94]
The documentation of `Subscription#close()` [says](https://github.com/nats-io/java-nats-streaming/blob/master/src/main/java/io/nats/streaming/Subscription.java#L61) the following

> <p>This call is equivalent to {@code close(false)}

However, [the implementation](https://github.com/nats-io/java-nats-streaming/blob/master/src/main/java/io/nats/streaming/SubscriptionImpl.java#L107) does following

```java
@Override
public void close() throws IOException {
    if (this.sc == null) {
        // already closed
        return;
    }
    close(true);
}
```

is that a bug?

**Comment by sasbury** [comment]
Agreed this is broken. I am working on a fix and will update shortly.

I was struggling with the fact that changing the code could break existing libraries, but I think the difference is important and am changing the code to match the doc.

**Comment by sasbury** [comment]
Assuming all is well with travis, I will release this with 2.0.2 in the next week or so.
