### ISSUE TITLE
Can I extend timeout ack for a 1 hour or more? 

### ISSUE THREAD

**Issue by tkgreg** [nats-io/java-nats-streaming#97]
I have next case: 
I received a message and I want to start processing it. Processing can take from 1 minute to 1 hour, Is it possible to extend an ack timeout?

**Comment by kozlovic** [comment]
You cannot do this on a per-message basis. You can set the AckWait only when creating the subscription.

**Comment by sasbury** [comment]
Closing - but let us know if you have any followups.
